### ISSUE TITLE
文档中的数据库初始化SQL脚本，少了很多表的创建语句

### ISSUE THREAD

**Issue by kkllwww007** [GrailStack/janus-admin#2]
文档中的数据库初始化SQL脚本，少了很多表的创建语句

**Comment by SoftwareKing** [comment]
@kkllwww007 加我微信私发给你Software_King

**Comment by WithoutCause** [comment]
https://github.com/GrailStack/janus-admin/blob/master/docs/db/1.0.0/ddl.sql
